#!/usr/bin/env python3
"""
生成初始迁移文件的脚本
"""
import os
from datetime import datetime

# 创建迁移文件
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
migration_content = f'''"""Initial migration

Revision ID: {timestamp}_initial
Revises: 
Create Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")}

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '{timestamp}_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Counters_id'), 'Counters', ['id'], unique=False)
    
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_openid', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('work_id', sa.String(length=50), nullable=True),
    sa.Column('is_solo_user', sa.Boolean(), nullable=True),
    sa.Column('is_supervisor', sa.Boolean(), nullable=True),
    sa.Column('is_community_worker', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Integer(), nullable=True),
    sa.Column('verification_materials', sa.Text(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_openid', 'users', ['wechat_openid'], unique=False)
    op.create_index('idx_phone', 'users', ['phone_number'], unique=False)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_index('idx_status', 'users', ['status'], unique=False)
    op.create_index('idx_verification_status', 'users', ['verification_status'], unique=False)
    
    op.create_table('checkin_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solo_user_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('frequency_type', sa.Integer(), nullable=False),
    sa.Column('time_slot_type', sa.Integer(), nullable=False),
    sa.Column('custom_time', sa.Time(), nullable=True),
    sa.Column('week_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('idx_solo_user_rules', 'checkin_rules', ['solo_user_id'], unique=False)
    op.create_index('idx_frequency_type', 'checkin_rules', ['frequency_type'], unique=False)
    op.create_index('idx_time_slot_type', 'checkin_rules', ['time_slot_type'], unique=False)
    op.create_index('idx_rule_status', 'checkin_rules', ['status'], unique=False)
    
    op.create_table('checkin_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('solo_user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('planned_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['checkin_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_rule_records', 'checkin_records', ['rule_id'], unique=False)
    op.create_index('idx_solo_user_records', 'checkin_records', ['solo_user_id'], unique=False)
    op.create_index('idx_planned_time', 'checkin_records', ['planned_time'], unique=False)
    op.create_index('idx_checkin_time', 'checkin_records', ['checkin_time'], unique=False)
    op.create_index('idx_record_status', 'checkin_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_record_status', table_name='checkin_records')
    op.drop_index('idx_checkin_time', table_name='checkin_records')
    op.drop_index('idx_planned_time', table_name='checkin_records')
    op.drop_index('idx_solo_user_records', table_name='checkin_records')
    op.drop_index('idx_rule_records', table_name='checkin_records')
    op.drop_table('checkin_records')
    op.drop_index('idx_rule_status', table_name='checkin_rules')
    op.drop_index('idx_time_slot_type', table_name='checkin_rules')
    op.drop_index('idx_frequency_type', table_name='checkin_rules')
    op.drop_index('idx_solo_user_rules', table_name='checkin_rules')
    op.drop_table('checkin_rules')
    op.drop_index('idx_verification_status', table_name='users')
    op.drop_index('idx_status', table_name='users')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_openid', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_Counters_id'), table_name='Counters')
    op.drop_table('Counters')
    # ### end Alembic commands ###
'''

# 写入迁移文件
migration_file = f"/Users/qiaoliang/working/code/safeGuard/backend/migrations/versions/{timestamp}_initial_migration.py"
with open(migration_file, 'w') as f:
    f.write(migration_content)

print(f"迁移文件已创建: {migration_file}")