FROM python:3.12

# 安装 ca-certificates 以支持 HTTPS
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 拷贝依赖文件
COPY requirements.txt requirements-test.txt ./

# 安装依赖
RUN pip install --user -r requirements.txt

# 暴露端口
EXPOSE 8080

# 设置基础启动命令
CMD ["python3", "run.py", "0.0.0.0", "8080"]