FROM python:3.12

# 设置工作目录
WORKDIR /app

# 拷贝依赖文件
COPY requirements.txt requirements-test.txt ./

# 安装依赖
RUN pip install --user -r requirements.txt

# 暴露端口
EXPOSE 8080

# 设置基础启动命令
# 注意：主程序已移至 src/main.py
#CMD ["python3", "src/main.py", "0.0.0.0", "8080"]