FROM safeguard-base:latest

# 设置工作目录
WORKDIR /app

# 拷贝项目文件
COPY . .

# 创建用于SQLite数据库的目录
RUN mkdir -p /app/data && chown -R 1000:1000 /app/data

# 设置环境变量
ENV ENV_TYPE=function
ENV SQLITE_DB_PATH=/app/data/app.db

# 暴露端口
EXPOSE 8080

# 执行启动命令
CMD ["python3", "run.py", "0.0.0.0", "8080"]