"""Add rule_supervisions table for rule-level supervision management

Revision ID: 20251202_160200
Revises: 20251201_213706
Create Date: 2025-12-02 16:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251202_160200'
down_revision = '20251201_213706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_supervisions',
    sa.Column('rule_supervision_id', sa.Integer(), nullable=False, comment='监护关系ID'),
    sa.Column('rule_id', sa.Integer(), nullable=False, comment='打卡规则ID'),
    sa.Column('solo_user_id', sa.Integer(), nullable=False, comment='独居者用户ID'),
    sa.Column('supervisor_user_id', sa.Integer(), nullable=False, comment='监护人用户ID'),
    sa.Column('status', sa.Integer(), nullable=True, comment='监护关系状态：0-待确认/1-已确认/2-已拒绝/3-已取消'),
    sa.Column('invitation_message', sa.Text(), nullable=True, comment='邀请消息'),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False, comment='邀请人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('responded_at', sa.DateTime(), nullable=True, comment='响应时间'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['checkin_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_supervision_id'),
    comment='规则监护关系表'
    )
    op.create_index('idx_rule_supervision', 'rule_supervisions', ['rule_id', 'supervisor_user_id'], unique=False)
    op.create_index('idx_solo_supervisions', 'rule_supervisions', ['solo_user_id', 'status'], unique=False)
    op.create_index('idx_supervisor_invitations', 'rule_supervisions', ['supervisor_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_supervisor_invitations', table_name='rule_supervisions')
    op.drop_index('idx_solo_supervisions', table_name='rule_supervisions')
    op.drop_index('idx_rule_supervision', table_name='rule_supervisions')
    op.drop_table('rule_supervisions')
    # ### end Alembic commands ###