"""初始数据库结构

Revision ID: 7788862c130d
Revises: 
Create Date: 2025-12-05 22:28:14.889525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7788862c130d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_link_access_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False, comment='分享链接token'),
    sa.Column('accessed_at', sa.DateTime(), nullable=True, comment='访问时间'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='访问者IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='UA'),
    sa.Column('supervisor_user_id', sa.Integer(), nullable=True, comment='解析后关联的监督者ID'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('share_link_access_logs', schema=None) as batch_op:
        batch_op.create_index('idx_share_log_token', ['token'], unique=False)

    op.create_table('user_audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('user_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_openid', sa.String(length=128), nullable=False, comment='微信OpenID，唯一标识用户'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号码，可用于登录和联系'),
    sa.Column('phone_hash', sa.String(length=64), nullable=True, comment='手机号加密哈希，用于安全查找'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='用户昵称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='用户头像URL'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='真实姓名'),
    sa.Column('work_id', sa.String(length=50), nullable=True, comment='工号或身份证号'),
    sa.Column('password_hash', sa.String(length=128), nullable=True, comment='密码哈希'),
    sa.Column('password_salt', sa.String(length=32), nullable=True, comment='密码盐'),
    sa.Column('role', sa.Integer(), nullable=False, comment='用户角色：1-独居者/2-监护人/3-社区工作人员'),
    sa.Column('status', sa.Integer(), nullable=True, comment='用户状态：1-正常/2-禁用'),
    sa.Column('verification_status', sa.Integer(), nullable=True, comment='验证状态：0-未申请/1-待审核/2-已通过/3-已拒绝'),
    sa.Column('verification_materials', sa.Text(), nullable=True, comment='验证材料URL'),
    sa.Column('is_solo_user', sa.Boolean(), nullable=True, comment='是否为打卡人'),
    sa.Column('is_supervisor', sa.Boolean(), nullable=True, comment='是否为监护人'),
    sa.Column('is_community_worker', sa.Boolean(), nullable=True, comment='是否为社区工作人员'),
    sa.Column('community_id', sa.Integer(), nullable=True, comment='所属社区ID，仅社区工作人员需要'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_hash'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('wechat_openid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_openid', ['wechat_openid'], unique=False)
        batch_op.create_index('idx_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_role', ['role'], unique=False)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index('idx_verif_phone_purpose', ['phone_number', 'purpose'], unique=False)

    op.create_table('checkin_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solo_user_id', sa.Integer(), nullable=False, comment='独居者用户ID'),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment='打卡规则名称，如：起床打卡、早餐打卡等'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='打卡事项图标URL'),
    sa.Column('frequency_type', sa.Integer(), nullable=False, comment='打卡频率类型：0-每天/1-每周/2-工作日/3-自定义'),
    sa.Column('time_slot_type', sa.Integer(), nullable=False, comment='时间段类型：1-上午/2-下午/3-晚上/4-自定义时间'),
    sa.Column('custom_time', sa.Time(), nullable=True, comment='自定义打卡时间'),
    sa.Column('custom_start_date', sa.Date(), nullable=True, comment='自定义开始日期'),
    sa.Column('custom_end_date', sa.Date(), nullable=True, comment='自定义结束日期'),
    sa.Column('week_days', sa.Integer(), nullable=True, comment='一周中的天（位掩码表示）：默认127表示周一到周日'),
    sa.Column('status', sa.Integer(), nullable=True, comment='规则状态：1-启用/0-禁用/2-已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('checkin_rules', schema=None) as batch_op:
        batch_op.create_index('idx_checkin_rules_solo_user', ['solo_user_id'], unique=False)
        batch_op.create_index('idx_checkin_rules_status', ['status'], unique=False)

    op.create_table('checkin_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False, comment='打卡规则ID'),
    sa.Column('solo_user_id', sa.Integer(), nullable=False, comment='独居者用户ID'),
    sa.Column('checkin_time', sa.DateTime(), nullable=True, comment='实际打卡时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-未打卡/1-已打卡/2-已撤销'),
    sa.Column('planned_time', sa.DateTime(), nullable=False, comment='计划打卡时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['rule_id'], ['checkin_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.create_index('idx_checkin_records_planned_time', ['planned_time'], unique=False)
        batch_op.create_index('idx_checkin_records_rule', ['rule_id'], unique=False)
        batch_op.create_index('idx_checkin_records_solo_user', ['solo_user_id'], unique=False)

    op.create_table('share_links',
    sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False, comment='分享链接token'),
    sa.Column('solo_user_id', sa.Integer(), nullable=False, comment='打卡人用户ID'),
    sa.Column('rule_id', sa.Integer(), nullable=False, comment='打卡规则ID'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['rule_id'], ['checkin_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index('idx_share_solo_rule', ['solo_user_id', 'rule_id'], unique=False)
        batch_op.create_index('idx_share_token', ['token'], unique=False)

    op.create_table('supervision_rule_relations',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solo_user_id', sa.Integer(), nullable=False, comment='被监督用户ID'),
    sa.Column('supervisor_user_id', sa.Integer(), nullable=True, comment='监督者用户ID（链接邀请时可为空，待绑定）'),
    sa.Column('rule_id', sa.Integer(), nullable=True, comment='具体规则ID，为空表示监督所有规则'),
    sa.Column('status', sa.Integer(), nullable=True, comment='关系状态：1-待同意/2-已同意/3-已拒绝/4-已移除'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('invite_token', sa.String(length=64), nullable=True, comment='邀请链接token'),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True, comment='邀请过期时间'),
    sa.ForeignKeyConstraint(['rule_id'], ['checkin_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['solo_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('invite_token')
    )
    with op.batch_alter_table('supervision_rule_relations', schema=None) as batch_op:
        batch_op.create_index('idx_solo_supervisor', ['solo_user_id', 'supervisor_user_id'], unique=False)
        batch_op.create_index('idx_supervisor_rule', ['supervisor_user_id', 'rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervision_rule_relations', schema=None) as batch_op:
        batch_op.drop_index('idx_supervisor_rule')
        batch_op.drop_index('idx_solo_supervisor')

    op.drop_table('supervision_rule_relations')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('idx_share_token')
        batch_op.drop_index('idx_share_solo_rule')

    op.drop_table('share_links')
    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.drop_index('idx_checkin_records_solo_user')
        batch_op.drop_index('idx_checkin_records_rule')
        batch_op.drop_index('idx_checkin_records_planned_time')

    op.drop_table('checkin_records')
    with op.batch_alter_table('checkin_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_checkin_rules_status')
        batch_op.drop_index('idx_checkin_rules_solo_user')

    op.drop_table('checkin_rules')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_verif_phone_purpose')

    op.drop_table('verification_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_role')
        batch_op.drop_index('idx_phone')
        batch_op.drop_index('idx_openid')

    op.drop_table('users')
    with op.batch_alter_table('user_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('user_audit_logs')
    with op.batch_alter_table('share_link_access_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_share_log_token')

    op.drop_table('share_link_access_logs')
    op.drop_table('Counters')
    # ### end Alembic commands ###
