"""add_user_medical_history_table

Revision ID: 20250108_add_user_medical_history_table
Revises:
Create Date: 2025-01-08

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20250108_add_user_medical_history_table'
down_revision = None  # This will be set when we know the previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_medical_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('condition_name', sa.String(length=100), nullable=False),
        sa.Column('treatment_plan', sa.Text(), nullable=True),
        sa.Column('visibility', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_medical_history_user_id'), 'user_medical_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_medical_history_user_id'), table_name='user_medical_history')
    op.drop_table('user_medical_history')
    # ### end Alembic commands ###
